= 用户手册

//@formatter:off

== 了解模板语法

模板引擎不同，编写模板时使用的语法也不同。
目前组件内置的模板引擎基于 https://velocity.apache.org[Velocity^] 实现。
文档中涉及的示例，也均使用 Velocity 语法。
组件默认启用了 https://velocity.apache.org/tools/3.1/[Velocity 工具^] 支持，
开发者可以使用其中丰富地扩展支持。

模板语法之间虽然有所差异，但最终达成的效果是相同的，都包括：

* 获取/设置变量值
* 判断
* 循环
* 调用方法
* 声明/调用宏

== 制作目录模板

常用的方式是基于已有代码制作目录模板。

开发某个功能时，意识到该功能和之前做过的某些功能，在代码上具有相似性。
此时可以考虑，基于之前的代码，制作目录模板。

浏览代码结构，确定哪些文件被忽略，哪些文件需要渲染，哪些文件直接拷贝。
需要渲染的模板文件后缀改为 *vm*，例如：*README.adoc* 改为 *README.adoc.vm*。
默认以 *vm* 结尾的文件会被渲染，其他文件直接拷贝。
如果默认规则不适用，可以通过选项属性文件更改。

使用 https://velocity.apache.org/engine/2.3/vtl-reference.html[VTL^] 语法，
修改模板文件的内容，同时整理出使用到的变量。
*变量描述文件* 约定为 *VARIABLE.adoc*，此文件默认被忽略，不会渲染到结果中。

在制作过程中，可以执行渲染，验证模板是否编写正确。
如确认无误，压缩目录和变量描述文件为 zip 包。
如果更改了选项，压缩时还应该包含 *选项属性文件*。
为了使用方便，还可以将 *变量属性文件* 也加入压缩包中。

以 xref:samples/antora.adoc[] 为例说明：

[source%nowrap,bash]
----
# 查看已准备文件
$ ls -l
drwxr-xr-x   6 xiayx  staff       192 Aug 10 05:39 antora # 目录模板
-rw-r--r--   1 xiayx  staff       192 Aug 10 05:39 antora-variable.adoc # 变量描述文件
-rw-r--r--   1 xiayx  staff        78 Aug  9 20:55 antora-options.properties   # 选项属性文件
-rw-r--r--   1 xiayx  staff       170 Aug 10 17:32 antora-variables.properties # 变量属性文件

# 仅打包目录和变量描述文件
$ zip -rq antora.zip antora antora-variable.adoc
# 同时打包选项属性文件
$ zip -rq antora.zip antora antora-variable.adoc antora-options.properties
# 同时打包变量属性文件
$ zip -rq antora.zip antora antora-variable.adoc antora-options.properties antora-variables.properties

# 打 jar 包
$ jar -cf antora.zip antora antora-variable.adoc antora-options.properties antora-variables.properties
----

目录模板的内容不受限制，可以实现各种各样的功能，满足了业务的复杂性。

== 渲染目录模板

有 2 种实现渲染目录模板的方式：编程和命令行。
以下代码示例均基于 *Antora 目录模板*。

=== 编程

如果是集成到 Java 项目中，可以使用该方式。

引用类库：

[source%nowrap,gradle,subs="specialchars,attributes"]
----
implementation "com.github.peacetrue.template:peacetrue-template-velocity:{latest-version}"
----

调用示例：

[source%nowrap,java]
----
include::example$peacetrue-template-engine/src/test/java/com/github/peacetrue/template/DirectoryTemplateEngineImplTest.java[tag=antora]
----

=== 命令行

下载 link:{attachmentsdir}/templates/template-engine.jar[目录模板引擎类库^]，
得到 template-engine.jar。

直接使用压缩包，基于类路径读取：

[source%nowrap,bash]
----
$ ls -l
-rw-r--r--  1 xiayx  staff     16751 Aug  8 13:05 antora.zip
-rw-r--r--  1 xiayx  staff  20143503 Aug 10 14:48 template-engine.jar

# 启动命令行
$ java -cp template-engine.jar:antora.zip org.springframework.boot.loader.JarLauncher

# 执行渲染命令
shell:> evaluate -t classpath:antora -o classpath:antora-options.properties -v classpath:antora-variables.properties -r learn

# 退出命令行
shell:> quit
----
// java -cp template-engine.jar:antora-module.zip org.springframework.boot.loader.JarLauncher
// evaluate -t classpath:antora-module -o classpath:antora-module-options.properties -v classpath:antora-module-variables.properties -r /Users/xiayx/Documents/Projects/peacetrue

解压压缩包，基于文件路径读取：

[source%nowrap,bash]
----
# 解压
$ unzip antora.zip

$ ls -l
drwxr-xr-x  1 xiayx  staff       192 Aug  8 13:05 antora # 目录模板
-rw-r--r--  1 xiayx  staff       192 Aug 10 05:39 antora-antora-variable.adoc # 变量描述文件
-rw-r--r--  1 xiayx  staff        78 Aug  9 20:55 antora-options.properties   # 选项属性文件
-rw-r--r--  1 xiayx  staff       170 Aug 10 17:32 antora-variables.properties # 变量属性文件
-rw-r--r--  1 xiayx  staff     16751 Aug  8 13:05 antora.zip
-rw-r--r--  1 xiayx  staff  20143503 Aug 10 14:48 template-engine.jar

# 启动命令行
$ java -jar template-engine.jar

# 执行渲染命令
shell:> evaluate -t file:antora -o file:antora-options.properties -v file:antora-variables.properties -r learn

# 退出命令行
shell:> quit
----
